[project]
name = "scheduler"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "ops>=2.9.0",
    "apscheduler>=3.10.0,<4",
    "charmlibs-systemd",
]

[dependency-groups]
unit = [
    "pytest",
    "coverage[toml]",
    "ops[testing]",
]
integration = [
    "jubilant>=1.9.0",
    "pytest-jubilant>=0.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
